In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

Saving gdp-worldbank.csv to gdp-worldbank (2).csv
Saving human-development-index.csv to human-development-index (2).csv
Saving improved-water-sources-vs-gdp-per-capita.csv to improved-water-sources-vs-gdp-per-capita (2).csv
Saving public_emdat_custom_request_2025-11-21_2d8c3622-d8e3-4a77-bd4b-b72013093c9c.xlsx to public_emdat_custom_request_2025-11-21_2d8c3622-d8e3-4a77-bd4b-b72013093c9c (2).xlsx
Saving public_emdat_custom_request_2025-11-21_d9b1c597-7944-4699-ab43-6d73937052e2.xlsx to public_emdat_custom_request_2025-11-21_d9b1c597-7944-4699-ab43-6d73937052e2 (2).xlsx
Saving urban-and-rural-population.csv to urban-and-rural-population (2).csv
Saving wgidataset_with_sourcedata.xlsx to wgidataset_with_sourcedata (2).xlsx

In [ ]:

gdp_total = pd.read_csv('gdp-worldbank.csv')
water_sources = pd.read_csv('improved-water-sources-vs-gdp-per-capita.csv')
population = pd.read_csv('urban-and-rural-population.csv')

# Read Excel
hdi_data = pd.read_csv('human-development-index.csv')

governance = pd.read_excel('wgidataset_with_sourcedata.xlsx')
disasters_natural = pd.read_excel('public_emdat_custom_request_2025-11-21_d9b1c597-7944-4699-ab43-6d73937052e2.xlsx')
disasters_tech = pd.read_excel('public_emdat_custom_request_2025-11-21_2d8c3622-d8e3-4a77-bd4b-b72013093c9c.xlsx')

In [ ]:
def show_columns(df, name):
    print("="*70)
    print(f" Columns in {name}:")
    print("="*70)
    for col in df.columns:
        print(col)
    print("\n\n")



show_columns(gdp_total, "GDP Total Dataset")
show_columns(water_sources, "Water Sources Dataset")
show_columns(population, "Population Dataset")
show_columns(governance, "Governance Dataset")
show_columns(disasters_natural, "Natural Disaster Dataset")
show_columns(disasters_tech, "Technological Disaster Dataset")

======================================================================
 Columns in GDP Total Dataset:
======================================================================
Entity
Code
Year
GDP, PPP (constant 2021 international $)



======================================================================
 Columns in Water Sources Dataset:
======================================================================
Entity
Code
Year
Share of the population using improved water sources
GDP per capita, PPP (constant 2021 international $)
World regions according to OWID



======================================================================
 Columns in Population Dataset:
======================================================================
Entity
Code
Year
Urban population
Rural population



======================================================================
 Columns in Governance Dataset:
======================================================================
codeindyr
code
countryname
year
indicator
estimate
stddev
nsource
pctrank
pctranklower
pctrankupper
adb
afr
asd
bps
bti
ccr
ebr
eiu
eqi
frh
gcb
gcs
gii
gwp
her
hum
hrm
ifd
ijt
ipd
irp
lbo
msi
obi
pia
prc
prs
rsf
tpr
vab
vdm
wbs
wcy
wjp
wmo
scalemean
scalesd



======================================================================
 Columns in Natural Disaster Dataset:
======================================================================
DisNo.
Historic
Classification Key
Disaster Group
Disaster Subgroup
Disaster Type
Disaster Subtype
External IDs
Event Name
ISO
Country
Subregion
Region
Location
Origin
Associated Types
OFDA/BHA Response
Appeal
Declaration
AID Contribution ('000 US$)
Magnitude
Magnitude Scale
Latitude
Longitude
River Basin
Start Year
Start Month
Start Day
End Year
End Month
End Day
Total Deaths
No. Injured
No. Affected
No. Homeless
Total Affected
Reconstruction Costs ('000 US$)
Reconstruction Costs, Adjusted ('000 US$)
Insured Damage ('000 US$)
Insured Damage, Adjusted ('000 US$)
Total Damage ('000 US$)
Total Damage, Adjusted ('000 US$)
CPI
Admin Units
Entry Date
Last Update



======================================================================
 Columns in Technological Disaster Dataset:
======================================================================
DisNo.
Historic
Classification Key
Disaster Group
Disaster Subgroup
Disaster Type
Disaster Subtype
External IDs
Event Name
ISO
Country
Subregion
Region
Location
Origin
Associated Types
OFDA/BHA Response
Appeal
Declaration
AID Contribution ('000 US$)
Magnitude
Magnitude Scale
Latitude
Longitude
River Basin
Start Year
Start Month
Start Day
End Year
End Month
End Day
Total Deaths
No. Injured
No. Affected
No. Homeless
Total Affected
Reconstruction Costs ('000 US$)
Reconstruction Costs, Adjusted ('000 US$)
Insured Damage ('000 US$)
Insured Damage, Adjusted ('000 US$)
Total Damage ('000 US$)
Total Damage, Adjusted ('000 US$)
CPI
Admin Units
Entry Date
Last Update

In [ ]:
merged = gdp_total.merge(
    water_sources,
    on=["Entity", "Code", "Year"],
    how="outer"
)

In [ ]:
merged.head()

,Entity,Code,Year,"GDP, PPP (constant 2021 international $)",Share of the population using improved water sources,"GDP per capita, PPP (constant 2021 international $)",World regions according to OWID
0,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN
1,Afghanistan,AFG,2001,2.949563e+10,30.773462,1454.1108,NaN
2,Afghanistan,AFG,2002,3.793138e+10,33.282040,1774.3087,NaN
3,Afghanistan,AFG,2003,4.128158e+10,35.789660,1815.9282,NaN
4,Afghanistan,AFG,2004,4.186536e+10,38.315050,1776.9182,NaN

In [ ]:
merged = merged.merge(
    population[['Entity','Code','Year','Urban population','Rural population']],
    on=['Entity','Code','Year'],
    how='left'
)

In [ ]:
merged.head()

,Entity,Code,Year,"GDP, PPP (constant 2021 international $)",Share of the population using improved water sources,"GDP per capita, PPP (constant 2021 international $)",World regions according to OWID,Urban population,Rural population
0,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0
1,Afghanistan,AFG,2001,2.949563e+10,30.773462,1454.1108,NaN,4496828.0,15787479.0
2,Afghanistan,AFG,2002,3.793138e+10,33.282040,1774.3087,NaN,4758983.0,16619134.0
3,Afghanistan,AFG,2003,4.128158e+10,35.789660,1815.9282,NaN,5081518.0,17651531.0
4,Afghanistan,AFG,2004,4.186536e+10,38.315050,1776.9182,NaN,5301147.0,18259507.0

In [ ]:
merged.columns

Index(['Entity', 'Code', 'Year', 'GDP, PPP (constant 2021 international $)',
       'Share of the population using improved water sources',
       'GDP per capita, PPP (constant 2021 international $)',
       'World regions according to OWID', 'Urban population',
       'Rural population'],
      dtype='object')

In [ ]:
merged['Year'] = merged['Year'].astype(int)
hdi_data['Year'] = hdi_data['Year'].astype(int)
merged['Entity'] = merged['Entity'].str.strip()
merged['Code'] = merged['Code'].str.strip()
hdi_data['Entity'] = hdi_data['Entity'].str.strip()
hdi_data['Code'] = hdi_data['Code'].str.strip()
print(set(merged['Code']) - set(hdi_data['Code']))
print(set(hdi_data['Code']) - set(merged['Code']))

{'OWID_CIS'}
set()

In [ ]:
# Only select the relevant columns from HDI to avoid duplicate 'World regions' columns
hdi_subset= hdi_data[['Entity', 'Code', 'Year', 'Human Development Index']]

# Merge with main dataset
merged = merged.merge(
    hdi_subset,
    on=['Entity', 'Code', 'Year'],
    how='left'
)

In [ ]:
merged.columns

Index(['Entity', 'Code', 'Year', 'GDP, PPP (constant 2021 international $)',
       'Share of the population using improved water sources',
       'GDP per capita, PPP (constant 2021 international $)',
       'World regions according to OWID', 'Urban population',
       'Rural population', 'Human Development Index'],
      dtype='object')

In [ ]:
merged.head()

,Entity,Code,Year,"GDP, PPP (constant 2021 international $)",Share of the population using improved water sources,"GDP per capita, PPP (constant 2021 international $)",World regions according to OWID,Urban population,Rural population,Human Development Index
0,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351
1,Afghanistan,AFG,2001,2.949563e+10,30.773462,1454.1108,NaN,4496828.0,15787479.0,0.355
2,Afghanistan,AFG,2002,3.793138e+10,33.282040,1774.3087,NaN,4758983.0,16619134.0,0.383
3,Afghanistan,AFG,2003,4.128158e+10,35.789660,1815.9282,NaN,5081518.0,17651531.0,0.392
4,Afghanistan,AFG,2004,4.186536e+10,38.315050,1776.9182,NaN,5301147.0,18259507.0,0.408

In [ ]:
gov_subset = governance[['code', 'countryname', 'year', 'indicator', 'estimate']]

gov_subset = gov_subset.rename(columns={
    'code': 'Code',
    'countryname': 'Entity',
    'year': 'Year'
})

In [ ]:
merged = merged.merge(
    gov_subset,
    on=['Entity', 'Code', 'Year'],
    how='left'
)

In [ ]:
merged.head()

,Entity,Code,Year,"GDP, PPP (constant 2021 international $)",Share of the population using improved water sources,"GDP per capita, PPP (constant 2021 international $)",World regions according to OWID,Urban population,Rural population,Human Development Index,indicator,estimate
0,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,cc,-1.271724
1,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,ge,-2.173946
2,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,pv,-2.438969
3,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,rl,-1.780661
4,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,rq,-2.080253

In [ ]:
merged.columns

Index(['Entity', 'Code', 'Year', 'GDP, PPP (constant 2021 international $)',
       'Share of the population using improved water sources',
       'GDP per capita, PPP (constant 2021 international $)',
       'World regions according to OWID', 'Urban population',
       'Rural population', 'Human Development Index', 'indicator', 'estimate'],
      dtype='object')

In [ ]:
disasters_subset = disasters_natural[[
    'Country', 'ISO', 'Start Year', 'Region',
    'Disaster Group', 'Disaster Type',
    'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless', 'Total Affected',
    "Total Damage ('000 US$)"
]]


disasters_subset = disasters_subset.rename(columns={
    'ISO': 'Code',
    'Country': 'Entity',
    'Start Year': 'Year'
})

In [ ]:

merged = merged.merge(
    disasters_subset,
    on=['Entity', 'Code', 'Year'],
    how='left'
)

In [ ]:
merged.columns

Index(['Entity', 'Code', 'Year', 'GDP, PPP (constant 2021 international $)',
       'Share of the population using improved water sources',
       'GDP per capita, PPP (constant 2021 international $)',
       'World regions according to OWID', 'Urban population',
       'Rural population', 'Human Development Index', 'indicator', 'estimate',
       'Region', 'Disaster Group', 'Disaster Type', 'Total Deaths',
       'No. Injured', 'No. Affected', 'No. Homeless', 'Total Affected',
       'Total Damage ('000 US$)'],
      dtype='object')

In [ ]:
merged.head()

,Entity,Code,Year,"GDP, PPP (constant 2021 international $)",Share of the population using improved water sources,"GDP per capita, PPP (constant 2021 international $)",World regions according to OWID,Urban population,Rural population,Human Development Index,...,estimate,Region,Disaster Group,Disaster Type,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Total Damage ('000 US$)
0,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,...,-1.271724,Asia,Natural,Epidemic,507.0,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,...,-1.271724,Asia,Natural,Epidemic,16.0,NaN,11.0,NaN,11.0,NaN
2,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,...,-1.271724,Asia,Natural,Epidemic,19.0,NaN,1604.0,NaN,1604.0,NaN
3,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,...,-1.271724,Asia,Natural,Epidemic,15.0,NaN,613.0,NaN,613.0,NaN
4,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,NaN,4444374.0,15685953.0,0.351,...,-1.271724,Asia,Natural,Drought,37.0,NaN,2580000.0,NaN,2580000.0,50.0

In [ ]:
# Keep only the required columns from technological disasters dataset
disasters_tech_subset = disasters_tech[[
    'ISO', 'Country', 'Region', 'Start Year',
    'Disaster Type',
    'Total Deaths', 'Total Affected', 'No. Affected',
    "Total Damage ('000 US$)", 'Disaster Group'
]]

# Rename columns to match your merged dataset
disasters_tech_subset = disasters_tech_subset.rename(columns={
    'ISO': 'Code',
    'Country': 'Entity',
    'Start Year': 'Year'
})

# Merge with your main dataset
merged = merged.merge(
    disasters_tech_subset,
    on=['Entity', 'Code', 'Year'],
    how='left',  # Keep all rows from your main dataset
    suffixes=('', '_tech')  # Avoid overwriting existing disaster columns
)

In [ ]:
merged.columns

Index(['Entity', 'Code', 'Year', 'GDP, PPP (constant 2021 international $)',
       'Share of the population using improved water sources',
       'GDP per capita, PPP (constant 2021 international $)',
       'World regions according to OWID', 'Urban population',
       'Rural population', 'Human Development Index', 'indicator', 'estimate',
       'Region', 'Disaster Group', 'Disaster Type', 'Total Deaths',
       'No. Injured', 'No. Affected', 'No. Homeless', 'Total Affected',
       'Total Damage ('000 US$)', 'Region_tech', 'Disaster Type_tech',
       'Total Deaths_tech', 'Total Affected_tech', 'No. Affected_tech',
       'Total Damage ('000 US$)_tech', 'Disaster Group_tech'],
      dtype='object')

In [ ]:
# 1. Fill missing Region using Region_tech
if 'Region' in merged.columns and 'Region_tech' in merged.columns:
    merged['Region'] = merged['Region'].fillna(merged['Region_tech'])

merged = merged.drop(
    columns=[
        'Region_tech',
        'World regions according to OWID',
    ],
    errors='ignore'
)

In [ ]:
merged.head()

,Entity,Code,Year,"GDP, PPP (constant 2021 international $)",Share of the population using improved water sources,"GDP per capita, PPP (constant 2021 international $)",Urban population,Rural population,Human Development Index,indicator,...,No. Affected,No. Homeless,Total Affected,Total Damage ('000 US$),Disaster Type_tech,Total Deaths_tech,Total Affected_tech,No. Affected_tech,Total Damage ('000 US$)_tech,Disaster Group_tech
0,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,4444374.0,15685953.0,0.351,cc,...,NaN,NaN,NaN,NaN,Collapse (Miscellaneous),40.0,40.0,NaN,NaN,Technological
1,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,4444374.0,15685953.0,0.351,cc,...,11.0,NaN,11.0,NaN,Collapse (Miscellaneous),40.0,40.0,NaN,NaN,Technological
2,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,4444374.0,15685953.0,0.351,cc,...,1604.0,NaN,1604.0,NaN,Collapse (Miscellaneous),40.0,40.0,NaN,NaN,Technological
3,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,4444374.0,15685953.0,0.351,cc,...,613.0,NaN,613.0,NaN,Collapse (Miscellaneous),40.0,40.0,NaN,NaN,Technological
4,Afghanistan,AFG,2000,3.256738e+10,30.741058,1617.8264,4444374.0,15685953.0,0.351,cc,...,2580000.0,NaN,2580000.0,50.0,Collapse (Miscellaneous),40.0,40.0,NaN,NaN,Technological

In [ ]:
merged.to_csv('Merged_Disasters_Dataset.csv', index=False)


files.download('Merged_Disasters_Dataset.csv')